mysql:
  build:
    context: ./mysql
  image: mysql:5.7
  container_name: "mysql"
  environment:
    - MYSQL_ROOT_PASSWORD=avlan
    - MYSQL_USER=avlan
    - MYSQL_PASSWORD=avlan
    - MYSQL_DATABASE=avlan
  volumes:
    - ./mysql:/var/lib/mysql
  external_links:
    - avlan:mysql.internal 

avlan:
  build:
    context: ./avlan
  image: avlan:latest
  container_name: "avlan"
  ports:
    - "3000:8000"
  links:
    - mysql
  volumes:
    - ./avlan/user_uploads:/app/user_uploads
    - ./avlan/webroot:/app/webroot
  external_links:
    - proxy:avlan.internal

nginx:
  build:
    context: ./nginx
  image: nginx:1.11
  container_name: "nginx"
  ports:
    - "80:80"
  environment:
    - NGINX_HOST=avlan.local
    - NGINX_PORT=80
  volumes:
    - ./avlan/webroot:/var/www/avlan:ro
    - ./nginx/nginx.tmpl:/etc/nginx/nginx.tmpl:ro
  command: /bin/bash -c "envsubst < /etc/nginx/nginx.tmpl > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
