version: "2"

services:
  mysql:
    build: ./mysql
    image: mysql:5.7
    container_name: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=avlan
      - MYSQL_USER=avlan
      - MYSQL_PASSWORD=avlan
      - MYSQL_DATABASE=avlan
    volumes:
      - ./mysql:/var/lib/mysql

  avlan:
    build: ./avlan
    image: avlan:latest
    depends_on:
      - mysql
    container_name: "avlan"
    restart: always
    ports:
      - "3000:8000"
    links:
      - mysql
    volumes:
      - ./avlan/user_uploads:/app/user_uploads
      - ./avlan/webroot:/app/webroot
    external_links:
      - mysql:mysql.internal

  nginx-proxy:
    build: ./nginx-proxy
    image: nginx-proxy:latest
    depends_on:
      - avlan
    container_name: "nginx"
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=avlan.local
      - NGINX_PORT=80
    volumes_from:
      - avlan:ro
    external_links:
      - avlan:avlan.internal
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/nginx.tmpl > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
