mysql:
  image: mysql
  container_name: "mysql"
  environment:
    - MYSQL_ROOT_PASSWORD=avlan
    - MYSQL_USER=avlan
    - MYSQL_PASSWORD=avlan
    - MYSQL_DATABASE=avlan
  volumes:
    - ./mysql:/var/lib/mysql

avlan:
  image: avlan
  container_name: "avlan"
  ports:
    - "3000:8000"
  links:
    - mysql
  volumes:
    - ./avlan/user_uploads:/app/user_uploads
    - ./avlan/webroot:/app/webroot
  external_links:
    - proxy:avlan.internal

proxy:
  image: nginx
  container_name: "nginx"
  ports:
    - "80:80"
  environment:
    - NGINX_HOST=avlan.local
  volumes:
    - ./avlan/webroot:/var/www/avlan:ro
    - ./nginx/conf.d:/etc/nginx/conf.d:ro
