version: "2"

services:
  avlan-mysql:
    build: ./avlan-mysql
    image: avlan-mysql:latest
    container_name: "avlan-mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=avlan
      - MYSQL_USER=avlan
      - MYSQL_PASSWORD=avlan
      - MYSQL_DATABASE=avlan
    volumes:
      - ./run/avlan-mysql:/var/lib/mysql

  avlan-redis:
    build: ./avlan-redis
    image: avlan-redis:latest
    container_name: "avlan-redis"

  avlan:
    build: ./avlan
    image: avlan:latest
    depends_on:
      - avlan-mysql
      - avlan-redis
    container_name: "avlan"
    restart: always
    ports:
      - "3000:8000"
    links:
      - avlan-mysql
    volumes:
      - ./run/avlan/storage:/app/storage
      - ./run/avlan/webroot:/app/webroot
    external_links:
      - avlan-mysql:mysql.internal
      - avlan-redis:redis.internal

  avlan-nginx:
    build: ./avlan-nginx
    image: avlan-nginx:latest
    depends_on:
      - avlan
    container_name: "avlan-nginx"
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=avlan.local
      - NGINX_PORT=80
      - APP_PORT=8000
    volumes_from:
      - avlan:ro
    external_links:
      - avlan:avlan.internal
    command: /bin/bash -c "envsubst '$$APP_PORT $$NGINX_HOST $$NGINX_PORT' < /etc/nginx/nginx.tmpl > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
